### ISSUE TITLE
BMP280

### ISSUE THREAD

**Issue by slowflyer** [PrzemoF/bmp183#1]
Hi,

can your code easly be modified to work with the newer BMP280 using SPI?

**Comment by PrzemoF** [comment]
My code would be a good starting point, but it's not just a matter of changing model number. There are C++ and C drivers available for BMP280 and a very detailed data sheet, so it shouldn't be hard if you know python and C++ or C.

**Comment by PrzemoF** [comment]
https://github.com/PrzemoF/bmp280
